# (C) Copyright Confidential Containers Contributors 2023.
# SPDX-License-Identifier: Apache-2.0
#
# Daily run the e2e tests.
---
name: daily e2e tests

on:
  schedule:
  # Runs "at 04:15(UTC time) every day" (see https://crontab.guru)
  # will base on default branch `stable`
    - cron: '15 4 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  e2e:
    uses: ./.github/workflows/e2e_run_all.yaml
    with:
      caa_image_tag: latest
      git_ref: refs/heads/stable
      podvm_image_tag: latest
      registry: docker.io/loricadev
    permissions:
      id-token: write
      contents: read
      packages: write
      attestations: write
    secrets:
      AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      REGISTRY_CREDENTIAL_ENCODED: ${{ secrets.REGISTRY_CREDENTIAL_ENCODED }}
